name: Test (Linux)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Test [no features]
        run: cargo test --verbose

      - name: Test ['tokio' feature]
        run: cargo test --verbose --features tokio

      - name: Test ['tokio-fs' feature]
        run: cargo test --verbose --features tokio-fs

      - name: Test compression features
        run: |
          for format in deflate bzip2 lzma zstd xz; do
            for suffix in '' '-read' '-write'; do
              cargo test --verbose --no-default-features --features "${format}${suffix}"
            done
          done
          cargo test --verbose --no-default-features --features deflate64
          cargo test --verbose --no-default-features --features deflate64-read

      - name: Test mixed compression features
        run: cargo test --verbose --no-default-features --features deflate-read,bzip2-write,lzma-read,zstd-write,xz-read,deflate64-read,tokio-fs

      - name: Test ['full' feature]
        run: cargo test --verbose --features full
